In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from typing import List, Tuple

pd.set_option('display.max_columns', None)

In [28]:
file_extension = "parquet"
CLIENTS_PATH: List[Tuple[str, str]] = [
    ("client-1: ToN", f"NF-TON-IOT-V2.{file_extension}"),
    ("client-2: BoT", f"NF-BOT-IOT-V2.{file_extension}"),
    ("client-3: UNSW", f"NF-UNSW-NB15-V2.{file_extension}"),
    ("client-4: CSE", f"NF-CSE-CIC-IDS2018-V2.{file_extension}"),
    ("centralized", f"centralized.{file_extension}"),
]

path_to_datasets = "../datasets/srs"
client_name, file_name = CLIENTS_PATH[3]
name = file_name.split(".")[0]

df = pd.read_parquet(f"{path_to_datasets}/{name}.parquet")
df = df.reset_index()
df = df.drop(columns=['index'])
df

,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,TCP_FLAGS,CLIENT_TCP_FLAGS,SERVER_TCP_FLAGS,FLOW_DURATION_MILLISECONDS,DURATION_IN,DURATION_OUT,MIN_TTL,MAX_TTL,LONGEST_FLOW_PKT,SHORTEST_FLOW_PKT,MIN_IP_PKT_LEN,MAX_IP_PKT_LEN,SRC_TO_DST_SECOND_BYTES,DST_TO_SRC_SECOND_BYTES,RETRANSMITTED_IN_BYTES,RETRANSMITTED_IN_PKTS,RETRANSMITTED_OUT_BYTES,RETRANSMITTED_OUT_PKTS,SRC_TO_DST_AVG_THROUGHPUT,DST_TO_SRC_AVG_THROUGHPUT,NUM_PKTS_UP_TO_128_BYTES,NUM_PKTS_128_TO_256_BYTES,NUM_PKTS_256_TO_512_BYTES,NUM_PKTS_512_TO_1024_BYTES,NUM_PKTS_1024_TO_1514_BYTES,TCP_WIN_MAX_IN,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,Label,Attack
0,18.218.115.60,59904,172.31.69.28,80,6,7.0,838,6,2102,5,219,219,27,0,0,0,127,127,1930,40,40,1930,838.0,2102.0,0,0,0,0,6704000,16816000,9,0,0,1,0,8192,26883,0,0,0,0,0,0,1,SQL Injection
1,18.218.115.60,49192,172.31.69.28,80,6,7.0,460,5,1147,5,219,219,27,4294965,1,1,127,127,975,40,40,975,460.0,1147.0,0,0,0,0,1840000,4584000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
2,18.218.115.60,56742,172.31.69.28,80,6,7.0,522,5,1147,5,219,219,27,4294945,21,21,127,127,975,40,40,975,522.0,1147.0,0,0,0,0,184000,416000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
3,18.218.115.60,49190,172.31.69.28,80,6,7.0,551,5,1147,5,219,219,27,4294942,24,24,127,127,975,40,40,975,551.0,1147.0,0,0,0,0,176000,360000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
4,18.218.115.60,57310,172.31.69.28,80,6,7.0,528,5,1147,5,219,219,27,4294939,28,28,127,127,975,40,40,975,528.0,1147.0,0,0,0,0,144000,312000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,89.103.22.162,45107,172.31.64.111,445,6,41.0,132,3,132,3,23,19,22,0,0,0,102,102,52,40,40,52,132.0,132.0,0,0,0,0,1056000,1056000,6,0,0,0,0,8192,8192,0,0,0,0,0,0,0,Benign
249996,172.31.67.91,52810,172.31.0.2,53,17,0.0,69,1,148,1,0,0,0,0,0,0,0,0,148,69,69,148,69.0,148.0,0,0,0,0,552000,1184000,1,1,0,0,0,0,0,0,0,26283,1,60,0,0,Benign
249997,172.31.65.61,54156,172.31.0.2,53,17,0.0,116,2,294,2,0,0,0,0,0,0,128,128,147,58,58,147,116.0,294.0,0,0,0,0,928000,2352000,2,2,0,0,0,0,0,0,0,43120,1,30,0,0,Benign
249998,177.153.5.106,50736,172.31.67.26,445,6,41.0,132,3,132,3,23,19,22,0,0,0,102,102,52,40,40,52,132.0,132.0,0,0,0,0,1056000,1056000,6,0,0,0,0,8192,8192,0,0,0,0,0,0,0,Benign
249999,172.31.67.29,51043,172.31.0.2,53,17,0.0,70,1,86,1,0,0,0,0,0,0,0,0,86,70,70,86,70.0,86.0,0,0,0,0,560000,688000,2,0,0,0,0,0,0,0,0,6849,1,60,0,0,Benign

In [29]:
df.describe()

/home/campos/college/PhoenixFL/prototype_1/.venv/lib/python3.10/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: overflow encountered in square
  sqr = _ensure_numeric((avg - values) ** 2)

,L4_SRC_PORT,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,TCP_FLAGS,CLIENT_TCP_FLAGS,SERVER_TCP_FLAGS,FLOW_DURATION_MILLISECONDS,DURATION_IN,DURATION_OUT,MIN_TTL,MAX_TTL,LONGEST_FLOW_PKT,SHORTEST_FLOW_PKT,MIN_IP_PKT_LEN,MAX_IP_PKT_LEN,SRC_TO_DST_SECOND_BYTES,DST_TO_SRC_SECOND_BYTES,RETRANSMITTED_IN_BYTES,RETRANSMITTED_IN_PKTS,RETRANSMITTED_OUT_BYTES,RETRANSMITTED_OUT_PKTS,SRC_TO_DST_AVG_THROUGHPUT,DST_TO_SRC_AVG_THROUGHPUT,NUM_PKTS_UP_TO_128_BYTES,NUM_PKTS_128_TO_256_BYTES,NUM_PKTS_256_TO_512_BYTES,NUM_PKTS_512_TO_1024_BYTES,NUM_PKTS_1024_TO_1514_BYTES,TCP_WIN_MAX_IN,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,Label
count,250000.000000,250000.000000,250000.000000,250000.000000,2.500000e+05,250000.00000,2.500000e+05,250000.000000,250000.000000,250000.000000,250000.000000,2.500000e+05,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,2.500000e+05,2.500000e+05,250000.000000,250000.000000,250000.000000,250000.000000,2.500000e+05,2.500000e+05,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.00000,250000.000000,250000.000000,250000.0,250000.00000
mean,52667.721244,1275.201604,10.550484,12.462525,1.790306e+03,23.20876,4.635794e+03,8.173636,76.502116,75.796380,21.306880,5.760504e+05,24.701880,11.420060,71.463540,71.567840,565.489716,53.588816,49.390896,565.489716,3.555556e+208,4.170876e+12,39.288376,0.548012,39.841344,0.110816,4.745498e+06,1.376487e+07,26.124932,1.334324,0.732356,0.600116,2.680336,11524.801992,20995.131868,3230.837704,12.620456,13372.23926,3.896128,19.141616,0.0,0.11952
std,11623.755878,3735.444158,5.430491,28.816955,6.656302e+04,1109.23684,2.182117e+05,147.908242,99.173668,98.935514,29.005649,1.463621e+06,1097.787762,80.072053,56.930634,57.038583,536.872901,36.630912,19.514694,536.872901,inf,2.082496e+15,312.933447,3.017957,825.827018,1.939789,1.003444e+07,9.253981e+07,1109.354089,5.020525,3.900301,3.248595,145.193367,19120.082202,25042.417975,12013.383148,46.927279,20135.86604,15.557719,26.352546,0.0,0.32440
min,0.000000,0.000000,1.000000,0.000000,2.800000e+01,1.00000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,28.000000,28.000000,0.000000,28.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.00000
25%,50732.000000,53.000000,6.000000,0.000000,6.900000e+01,1.00000,1.170000e+02,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,100.000000,40.000000,40.000000,100.000000,7.000000e+01,1.210000e+02,0.000000,0.000000,0.000000,0.000000,5.200000e+05,7.600000e+05,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.00000
50%,54193.000000,80.000000,6.000000,0.000000,1.920000e+02,4.00000,3.240000e+02,3.000000,27.000000,26.000000,22.000000,0.000000e+00,0.000000,0.000000,101.000000,101.000000,192.000000,40.000000,40.000000,192.000000,2.140000e+02,3.400000e+02,0.000000,0.000000,0.000000,0.000000,9.920000e+05,1.424000e+06,6.000000,1.000000,0.000000,0.000000,0.000000,8192.000000,8192.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.00000
75%,59502.000000,445.000000,17.000000,7.000000,1.460000e+03,9.00000,1.873000e+03,7.000000,219.000000,219.000000,27.000000,0.000000e+00,0.000000,0.000000,128.000000,128.000000,1189.000000,66.000000,65.000000,1189.000000,1.460000e+03,1.873000e+03,0.000000,0.000000,0.000000,0.000000,9.096000e+06,1.376800e+07,12.000000,2.000000,1.000000,1.000000,1.000000,8192.000000,29200.000000,0.000000,0.000000,25365.25000,1.000000,60.000000,0.0,0.00000
max,65535.000000,65535.000000,58.000000,248.000000,1.142682e+07,190447.00000,4.176905e+07,27909.000000,223.000000,223.000000,223.000000,4.294967e+06,106638.000000,15008.000000,255.000000,255.000000,1975.000000,1478.000000,330.000000,1975.000000,8.888889e+213,1.041248e+18,73051.000000,301.000000,210141.000000,645.000000,1.522864e+09,4.275977e+09,190447.000000,595.000000,476.000000,1203.000000,27828.000000,65535.000000,65535.000000,65280.000000,255.000000,65535.00000,255.000000,60.000000,0.0,1.00000

In [37]:
df['SRC_TO_DST_SECOND_BYTES'].nlargest(10)

111639    8.888889e+213
98557     8.888889e+201
237729    8.888889e+201
166566    8.888889e+199
234217     3.306691e+24
237076     3.508806e+22
100710     3.807601e+17
87910      1.443041e+17
28         7.224012e+16
45         9.600060e+13
Name: SRC_TO_DST_SECOND_BYTES, dtype: float64

In [36]:
#df.iloc[166566]

In [38]:
filtered_df = df.drop([111639, 98557, 237729, 166566])

In [25]:
filtered_df = df

In [39]:
filtered_df['SRC_TO_DST_SECOND_BYTES'].describe()

count    2.499960e+05
mean     1.336733e+19
std      6.613807e+21
min      0.000000e+00
25%      7.000000e+01
50%      2.140000e+02
75%      1.460000e+03
max      3.306691e+24
Name: SRC_TO_DST_SECOND_BYTES, dtype: float64

In [40]:
filtered_df

,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,TCP_FLAGS,CLIENT_TCP_FLAGS,SERVER_TCP_FLAGS,FLOW_DURATION_MILLISECONDS,DURATION_IN,DURATION_OUT,MIN_TTL,MAX_TTL,LONGEST_FLOW_PKT,SHORTEST_FLOW_PKT,MIN_IP_PKT_LEN,MAX_IP_PKT_LEN,SRC_TO_DST_SECOND_BYTES,DST_TO_SRC_SECOND_BYTES,RETRANSMITTED_IN_BYTES,RETRANSMITTED_IN_PKTS,RETRANSMITTED_OUT_BYTES,RETRANSMITTED_OUT_PKTS,SRC_TO_DST_AVG_THROUGHPUT,DST_TO_SRC_AVG_THROUGHPUT,NUM_PKTS_UP_TO_128_BYTES,NUM_PKTS_128_TO_256_BYTES,NUM_PKTS_256_TO_512_BYTES,NUM_PKTS_512_TO_1024_BYTES,NUM_PKTS_1024_TO_1514_BYTES,TCP_WIN_MAX_IN,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,Label,Attack
0,18.218.115.60,59904,172.31.69.28,80,6,7.0,838,6,2102,5,219,219,27,0,0,0,127,127,1930,40,40,1930,838.0,2102.0,0,0,0,0,6704000,16816000,9,0,0,1,0,8192,26883,0,0,0,0,0,0,1,SQL Injection
1,18.218.115.60,49192,172.31.69.28,80,6,7.0,460,5,1147,5,219,219,27,4294965,1,1,127,127,975,40,40,975,460.0,1147.0,0,0,0,0,1840000,4584000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
2,18.218.115.60,56742,172.31.69.28,80,6,7.0,522,5,1147,5,219,219,27,4294945,21,21,127,127,975,40,40,975,522.0,1147.0,0,0,0,0,184000,416000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
3,18.218.115.60,49190,172.31.69.28,80,6,7.0,551,5,1147,5,219,219,27,4294942,24,24,127,127,975,40,40,975,551.0,1147.0,0,0,0,0,176000,360000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
4,18.218.115.60,57310,172.31.69.28,80,6,7.0,528,5,1147,5,219,219,27,4294939,28,28,127,127,975,40,40,975,528.0,1147.0,0,0,0,0,144000,312000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,89.103.22.162,45107,172.31.64.111,445,6,41.0,132,3,132,3,23,19,22,0,0,0,102,102,52,40,40,52,132.0,132.0,0,0,0,0,1056000,1056000,6,0,0,0,0,8192,8192,0,0,0,0,0,0,0,Benign
249996,172.31.67.91,52810,172.31.0.2,53,17,0.0,69,1,148,1,0,0,0,0,0,0,0,0,148,69,69,148,69.0,148.0,0,0,0,0,552000,1184000,1,1,0,0,0,0,0,0,0,26283,1,60,0,0,Benign
249997,172.31.65.61,54156,172.31.0.2,53,17,0.0,116,2,294,2,0,0,0,0,0,0,128,128,147,58,58,147,116.0,294.0,0,0,0,0,928000,2352000,2,2,0,0,0,0,0,0,0,43120,1,30,0,0,Benign
249998,177.153.5.106,50736,172.31.67.26,445,6,41.0,132,3,132,3,23,19,22,0,0,0,102,102,52,40,40,52,132.0,132.0,0,0,0,0,1056000,1056000,6,0,0,0,0,8192,8192,0,0,0,0,0,0,0,Benign
249999,172.31.67.29,51043,172.31.0.2,53,17,0.0,70,1,86,1,0,0,0,0,0,0,0,0,86,70,70,86,70.0,86.0,0,0,0,0,560000,688000,2,0,0,0,0,0,0,0,0,6849,1,60,0,0,Benign

In [41]:
filtered_df.to_parquet(f'./../datasets/pre-processed/phoenix/{name}.parquet')