In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from typing import List, Tuple

pd.set_option('display.max_columns', None)

In [23]:
file_extension = "parquet"
CLIENTS_PATH: List[Tuple[str, str]] = [
    ("client-1: ToN", f"NF-TON-IOT-V2.{file_extension}"),
    ("client-2: BoT", f"NF-BOT-IOT-V2.{file_extension}"),
    ("client-3: UNSW", f"NF-UNSW-NB15-V2.{file_extension}"),
    ("client-4: CSE", f"NF-CSE-CIC-IDS2018-V2.{file_extension}"),
    ("centralized", f"centralized.{file_extension}"),
]

path_to_datasets = "../datasets/srs"
client_name, file_name = CLIENTS_PATH[3]
name = file_name.split(".")[0]

df = pd.read_parquet(f"{path_to_datasets}/{name}.parquet")
df = df.reset_index()
df = df.drop(columns=['index'])
df.head()

,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,TCP_FLAGS,CLIENT_TCP_FLAGS,SERVER_TCP_FLAGS,FLOW_DURATION_MILLISECONDS,DURATION_IN,DURATION_OUT,MIN_TTL,MAX_TTL,LONGEST_FLOW_PKT,SHORTEST_FLOW_PKT,MIN_IP_PKT_LEN,MAX_IP_PKT_LEN,SRC_TO_DST_SECOND_BYTES,DST_TO_SRC_SECOND_BYTES,RETRANSMITTED_IN_BYTES,RETRANSMITTED_IN_PKTS,RETRANSMITTED_OUT_BYTES,RETRANSMITTED_OUT_PKTS,SRC_TO_DST_AVG_THROUGHPUT,DST_TO_SRC_AVG_THROUGHPUT,NUM_PKTS_UP_TO_128_BYTES,NUM_PKTS_128_TO_256_BYTES,NUM_PKTS_256_TO_512_BYTES,NUM_PKTS_512_TO_1024_BYTES,NUM_PKTS_1024_TO_1514_BYTES,TCP_WIN_MAX_IN,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,Label,Attack
0,18.218.115.60,49227,172.31.69.28,80,6,7.0,500,5,1147,5,219,219,27,4294948,18,18,127,127,975,40,40,975,500.0,1147.0,0,0,0,0,208000,480000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
1,18.218.115.60,49211,172.31.69.28,80,6,7.0,459,5,1147,5,219,219,27,4294960,6,6,127,127,975,40,40,975,459.0,1147.0,0,0,0,0,520000,1304000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
2,18.218.115.60,49183,172.31.69.28,80,6,7.0,854,6,2045,4,219,219,27,4294951,16,16,127,127,1913,40,40,1913,854.0,2045.0,0,0,0,0,400000,960000,8,0,0,1,0,8192,26883,0,0,0,0,0,0,1,SQL Injection
3,18.218.115.60,59887,172.31.69.28,80,6,7.0,528,5,1147,5,219,219,27,4294938,29,29,127,127,975,40,40,975,528.0,1147.0,0,0,0,0,136000,304000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
4,18.218.115.60,55482,172.31.69.28,80,6,7.0,528,5,1147,5,219,219,27,4294945,21,21,127,127,975,40,40,975,528.0,1147.0,0,0,0,0,192000,416000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,Brute Force -XSS

In [24]:
df.describe()

/home/campos/college/PhoenixFL/prototype_1/.venv/lib/python3.10/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: overflow encountered in square
  sqr = _ensure_numeric((avg - values) ** 2)

,L4_SRC_PORT,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,TCP_FLAGS,CLIENT_TCP_FLAGS,SERVER_TCP_FLAGS,FLOW_DURATION_MILLISECONDS,DURATION_IN,DURATION_OUT,MIN_TTL,MAX_TTL,LONGEST_FLOW_PKT,SHORTEST_FLOW_PKT,MIN_IP_PKT_LEN,MAX_IP_PKT_LEN,SRC_TO_DST_SECOND_BYTES,DST_TO_SRC_SECOND_BYTES,RETRANSMITTED_IN_BYTES,RETRANSMITTED_IN_PKTS,RETRANSMITTED_OUT_BYTES,RETRANSMITTED_OUT_PKTS,SRC_TO_DST_AVG_THROUGHPUT,DST_TO_SRC_AVG_THROUGHPUT,NUM_PKTS_UP_TO_128_BYTES,NUM_PKTS_128_TO_256_BYTES,NUM_PKTS_256_TO_512_BYTES,NUM_PKTS_512_TO_1024_BYTES,NUM_PKTS_1024_TO_1514_BYTES,TCP_WIN_MAX_IN,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,Label
count,188936.000000,188936.000000,188936.000000,188936.000000,1.889360e+05,188936.000000,1.889360e+05,188936.000000,188936.000000,188936.000000,188936.000000,1.889360e+05,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,1.889360e+05,1.889360e+05,188936.000000,188936.000000,188936.000000,188936.000000,1.889360e+05,1.889360e+05,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.000000,188936.0,188936.000000
mean,52627.484863,1272.052949,10.542755,12.450826,1.795340e+03,23.545089,8.450433e+03,10.835500,76.144451,75.434168,21.251710,5.724223e+05,24.662743,11.206578,71.391117,71.492447,564.688291,53.450745,49.394292,564.688291,4.704709e+204,2.522320e+12,38.255436,0.543756,44.319918,0.108555,4.785476e+06,1.424816e+07,26.505097,1.337950,0.750238,0.621909,5.254467,11504.086241,20989.594820,3239.126440,12.652835,13333.772595,3.869146,19.105708,0.0,0.119511
std,11660.061680,3698.679349,5.434774,28.793897,6.474515e+04,1082.850989,5.274051e+05,361.238663,98.996751,98.764362,28.847301,1.459717e+06,1098.199715,71.452427,56.932349,57.036208,536.640806,34.356217,19.590719,536.640806,inf,1.093982e+15,271.310119,2.965396,1283.225268,1.538114,1.094194e+07,1.001022e+08,1083.039771,5.611666,4.713789,4.451964,355.106931,19082.943050,25047.117613,12052.336441,47.079440,20114.719161,15.320929,26.333976,0.0,0.324390
min,0.000000,0.000000,1.000000,0.000000,2.800000e+01,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,28.000000,28.000000,0.000000,28.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,50732.000000,53.000000,6.000000,0.000000,6.900000e+01,1.000000,1.170000e+02,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,100.000000,40.000000,40.000000,100.000000,7.000000e+01,1.210000e+02,0.000000,0.000000,0.000000,0.000000,5.200000e+05,7.600000e+05,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
50%,54189.000000,80.000000,6.000000,0.000000,1.800000e+02,4.000000,3.240000e+02,3.000000,27.000000,26.000000,22.000000,0.000000e+00,0.000000,0.000000,100.000000,100.000000,192.000000,40.000000,40.000000,192.000000,2.050000e+02,3.380000e+02,0.000000,0.000000,0.000000,0.000000,9.920000e+05,1.456000e+06,6.000000,1.000000,0.000000,0.000000,0.000000,8192.000000,8192.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
75%,59471.250000,445.000000,17.000000,7.000000,1.460000e+03,9.000000,1.873000e+03,7.000000,219.000000,219.000000,27.000000,0.000000e+00,0.000000,0.000000,128.000000,128.000000,1189.000000,66.000000,65.000000,1189.000000,1.460000e+03,1.873000e+03,0.000000,0.000000,0.000000,0.000000,9.096000e+06,1.376800e+07,12.000000,2.000000,1.000000,1.000000,1.000000,8192.000000,29200.000000,0.000000,0.000000,25257.250000,1.000000,60.000000,0.0,0.000000
max,65535.000000,65535.000000,58.000000,248.000000,7.646280e+06,127438.000000,9.942216e+07,66951.000000,223.000000,223.000000,223.000000,4.294967e+06,106636.000000,4969.000000,255.000000,255.000000,2945.000000,1478.000000,330.000000,2945.000000,8.888889e+209,4.755185e+17,13864.000000,142.000000,352750.000000,236.000000,1.711056e+09,4.280857e+09,127438.000000,941.000000,568.000000,1193.000000,66091.000000,65535.000000,65535.000000,65280.000000,255.000000,65535.000000,255.000000,60.000000,0.0,1.000000

In [26]:
df['SRC_TO_DST_SECOND_BYTES'].nlargest(10)

98555     8.888889e+209
167784     2.686478e+18
30006      3.767253e+15
54         5.285285e+14
865        9.340107e+12
951        3.288625e+12
984        3.236637e+12
838        3.232635e+12
909        3.220642e+12
1022       3.220632e+12
Name: SRC_TO_DST_SECOND_BYTES, dtype: float64

In [9]:
# df.iloc[98555]

In [27]:
filtered_df = df.drop([98555])

In [21]:
filtered_df = df

In [28]:
filtered_df['SRC_TO_DST_SECOND_BYTES'].describe()

count    1.889350e+05
mean     1.424245e+13
std      6.180556e+15
min      0.000000e+00
25%      7.000000e+01
50%      2.050000e+02
75%      1.460000e+03
max      2.686478e+18
Name: SRC_TO_DST_SECOND_BYTES, dtype: float64

In [29]:
filtered_df

,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,TCP_FLAGS,CLIENT_TCP_FLAGS,SERVER_TCP_FLAGS,FLOW_DURATION_MILLISECONDS,DURATION_IN,DURATION_OUT,MIN_TTL,MAX_TTL,LONGEST_FLOW_PKT,SHORTEST_FLOW_PKT,MIN_IP_PKT_LEN,MAX_IP_PKT_LEN,SRC_TO_DST_SECOND_BYTES,DST_TO_SRC_SECOND_BYTES,RETRANSMITTED_IN_BYTES,RETRANSMITTED_IN_PKTS,RETRANSMITTED_OUT_BYTES,RETRANSMITTED_OUT_PKTS,SRC_TO_DST_AVG_THROUGHPUT,DST_TO_SRC_AVG_THROUGHPUT,NUM_PKTS_UP_TO_128_BYTES,NUM_PKTS_128_TO_256_BYTES,NUM_PKTS_256_TO_512_BYTES,NUM_PKTS_512_TO_1024_BYTES,NUM_PKTS_1024_TO_1514_BYTES,TCP_WIN_MAX_IN,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,Label,Attack
0,18.218.115.60,49227,172.31.69.28,80,6,7.000,500,5,1147,5,219,219,27,4294948,18,18,127,127,975,40,40,975,500.0,1147.0,0,0,0,0,208000,480000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
1,18.218.115.60,49211,172.31.69.28,80,6,7.000,459,5,1147,5,219,219,27,4294960,6,6,127,127,975,40,40,975,459.0,1147.0,0,0,0,0,520000,1304000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
2,18.218.115.60,49183,172.31.69.28,80,6,7.000,854,6,2045,4,219,219,27,4294951,16,16,127,127,1913,40,40,1913,854.0,2045.0,0,0,0,0,400000,960000,8,0,0,1,0,8192,26883,0,0,0,0,0,0,1,SQL Injection
3,18.218.115.60,59887,172.31.69.28,80,6,7.000,528,5,1147,5,219,219,27,4294938,29,29,127,127,975,40,40,975,528.0,1147.0,0,0,0,0,136000,304000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,SQL Injection
4,18.218.115.60,55482,172.31.69.28,80,6,7.000,528,5,1147,5,219,219,27,4294945,21,21,127,127,975,40,40,975,528.0,1147.0,0,0,0,0,192000,416000,8,0,1,1,0,65535,26883,0,0,0,0,0,0,1,Brute Force -XSS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188931,172.31.66.76,52932,68.67.178.138,443,6,0.000,901,8,1523,10,27,27,27,0,0,0,128,128,972,40,40,972,901.0,1523.0,41,1,0,0,7208000,12184000,15,1,0,2,0,64240,36500,10496,41,0,0,0,0,0,Benign
188932,5.188.9.25,50099,172.31.65.125,62518,6,0.000,40,1,0,0,2,2,0,0,0,0,0,0,40,40,0,40,40.0,0.0,0,0,0,0,320000,0,1,0,0,0,0,1024,0,0,0,0,0,0,0,0,Benign
188933,172.31.66.37,52538,172.31.0.2,53,17,0.000,124,2,306,2,0,0,0,0,0,0,128,128,153,62,62,153,124.0,306.0,0,0,0,0,992000,2448000,2,2,0,0,0,0,0,0,0,51038,1,60,0,0,Benign
188934,45.65.220.6,53395,172.31.64.106,445,6,41.000,132,3,132,3,23,19,22,0,0,0,103,103,52,40,40,52,132.0,132.0,0,0,0,0,1056000,1056000,6,0,0,0,0,16567,8192,0,0,0,0,0,0,0,Benign
188935,172.31.66.65,55316,172.31.0.2,53,17,5.126,70,1,86,1,0,0,0,0,0,0,0,0,86,70,70,86,70.0,86.0,0,0,0,0,560000,688000,2,0,0,0,0,0,0,0,0,1694,1,59,0,0,Benign

In [30]:
filtered_df.to_parquet(f'./../datasets/pre-processed/phoenix/{name}.parquet')